Add publisher omnibus service

diff --git a/deploy/omnibus-cache/our_init b/deploy/omnibus-cache/our_init
--- a/deploy/omnibus-cache/our_init
+++ b/deploy/omnibus-cache/our_init
@@ -4,9 +4,13 @@
 chown root:root /var/log
 chmod 0755 /var/log
 
+# if omnibus isn't enabled, exec directly
+if [ -z "${OMNIBUS}" ]; then
+    exec "$@"
+fi
+
 # write filebeat config
-set +u
-if test "x${ELASTICSEARCH_URL-}" = "x"; then
+if [ -z "${ELASTICSEARCH_URL}" ]; then
     # Prevent filebeat from starting if we don't know where it should forward logs.
     echo >&2 'No ELASTICSEARCH_URL set; will not forward logs.'
     touch /etc/service/filebeat/down
@@ -14,7 +18,30 @@ else
     echo >&2 "Forwarding logs to: ${ELASTICSEARCH_URL}"
     sed 's#{{ELASTICSEARCH_URL}}#'"${ELASTICSEARCH_URL}"'#g' /etc/filebeat.yml.tpl > /etc/filebeat.yml
 fi
-set -u
+
+if [ $# -ne 1 ]; then
+    echo 'ERROR: when starting the omnibus service, only a single argument is expected'
+    exit 1
+fi
+
+# disable all services
+for x in cache publisher; do
+    touch "/etc/service/${x}/down"
+done
+
+# re-enable the one we want
+case "$1" in
+    cache)
+        rm "/etc/service/cache/down"
+        ;;
+    publisher)
+        rm "/etc/service/publisher/down"
+        ;;
+    *)
+        echo "ERROR: unknown service: $1"
+        exit 1
+        ;;
+esac
 
 # spawn services
 exec runsvdir -P /etc/service
